apiVersion: v1
kind: ServiceAccount
metadata:
  {{- if .Values.sa.roleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.sa.roleArn }}
  {{- end }}
  labels:
    app: mirrord-operator
  name: {{ .Values.sa.name }}
  namespace: {{ .Values.namespace }}
